import { pgTable, text, timestamp, integer, real, boolean, jsonb } from "drizzle-orm/pg-core"

export const productFiscal = pgTable("product_fiscal", {
  id: text("id").primaryKey(),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
  deleted_at: timestamp("deleted_at"),

  product_id: text("product_id"),
  ncm: text("ncm"),
  cest: text("cest"),
  origem: integer("origem").default(0),
  cst_icms: text("cst_icms"),
  csosn: text("csosn"),
  cfop_dentro_estado: text("cfop_dentro_estado"),
  cfop_fora_estado: text("cfop_fora_estado"),
  aliquota_icms: real("aliquota_icms"),
  aliquota_icms_st: real("aliquota_icms_st"),
  mva_st: real("mva_st"),
  reducao_bc_icms: real("reducao_bc_icms"),
  fcp: real("fcp"),
  icms_desonerado: boolean("icms_desonerado").default(false),
  cst_pis: text("cst_pis"),
  aliquota_pis: real("aliquota_pis"),
  cst_cofins: text("cst_cofins"),
  aliquota_cofins: real("aliquota_cofins"),
  cst_ipi: text("cst_ipi"),
  aliquota_ipi: real("aliquota_ipi"),
  codigo_enquadramento_ipi: text("codigo_enquadramento_ipi"),
  unidade_comercial: text("unidade_comercial").default("UN"),
  unidade_tributavel: text("unidade_tributavel").default("UN"),
  peso_liquido: real("peso_liquido"),
  peso_bruto: real("peso_bruto"),
  gtin: text("gtin"),
  gtin_tributavel: text("gtin_tributavel"),
  codigo_beneficio_fiscal: text("codigo_beneficio_fiscal"),
  info_adicional: text("info_adicional"),
  ex_tipi: text("ex_tipi"),
  metadata: jsonb("metadata"),
})

export const storeFiscalConfig = pgTable("store_fiscal_config", {
  id: text("id").primaryKey(),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
  deleted_at: timestamp("deleted_at"),

  razao_social: text("razao_social"),
  nome_fantasia: text("nome_fantasia"),
  cnpj: text("cnpj"),
  inscricao_estadual: text("inscricao_estadual"),
  inscricao_municipal: text("inscricao_municipal"),
  regime_tributario: text("regime_tributario").default("simples_nacional"),
  cep: text("cep"),
  logradouro: text("logradouro"),
  numero: text("numero"),
  complemento: text("complemento"),
  bairro: text("bairro"),
  cidade: text("cidade"),
  uf: text("uf"),
  codigo_municipio: text("codigo_municipio"),
  ncm_padrao: text("ncm_padrao"),
  cest_padrao: text("cest_padrao"),
  origem_padrao: integer("origem_padrao").default(0),
  cst_icms_padrao: text("cst_icms_padrao"),
  csosn_padrao: text("csosn_padrao"),
  cfop_dentro_estado: text("cfop_dentro_estado"),
  cfop_fora_estado: text("cfop_fora_estado"),
  aliquota_icms: real("aliquota_icms"),
  aliquota_icms_st: real("aliquota_icms_st"),
  mva_st: real("mva_st"),
  reducao_bc_icms: real("reducao_bc_icms"),
  fcp: real("fcp"),
  cst_pis_padrao: text("cst_pis_padrao"),
  aliquota_pis: real("aliquota_pis"),
  cst_cofins_padrao: text("cst_cofins_padrao"),
  aliquota_cofins: real("aliquota_cofins"),
  cst_ipi_padrao: text("cst_ipi_padrao"),
  aliquota_ipi: real("aliquota_ipi"),
  codigo_enquadramento_ipi: text("codigo_enquadramento_ipi"),
  unidade_comercial: text("unidade_comercial").default("UN"),
  unidade_tributavel: text("unidade_tributavel").default("UN"),
  serie_nfe: text("serie_nfe").default("1"),
  ambiente: text("ambiente").default("homologacao"),
  tipo_emissao: text("tipo_emissao").default("normal"),
  natureza_operacao: text("natureza_operacao").default("Venda de mercadoria"),
  info_complementar: text("info_complementar"),
  metadata: jsonb("metadata"),
})

export const nfeRegistro = pgTable("nfe_registro", {
  id: text("id").primaryKey(),
  tipo: text("tipo").notNull().default("saida"),
  numero: integer("numero"),
  serie: integer("serie").default(3),
  chave_acesso: text("chave_acesso"),
  protocolo: text("protocolo"),
  status: text("status").default("pendente"),
  order_id: text("order_id"),
  customer_name: text("customer_name"),
  customer_cpf: text("customer_cpf"),
  valor_total: integer("valor_total").default(0),
  xml: text("xml"),
  danfe_base64: text("danfe_base64"),
  motivo_rejeicao: text("motivo_rejeicao"),
  motivo_cancelamento: text("motivo_cancelamento"),
  cfop: text("cfop"),
  natureza_operacao: text("natureza_operacao").default("Venda de mercadoria"),
  nfe_referenciada: text("nfe_referenciada"),
  metadata: jsonb("metadata"),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
})
