import { pgTable, text, timestamp, integer, jsonb } from "drizzle-orm/pg-core"

export const astroOrder = pgTable("astro_order", {
  id: text("id").primaryKey(),
  display_id: text("display_id"),
  status: text("status").default("pending"),
  customer_id: text("customer_id"),
  customer_name: text("customer_name"),
  customer_email: text("customer_email"),
  items: jsonb("items").default([]),
  subtotal: integer("subtotal").default(0),
  shipping_cost: integer("shipping_cost").default(0),
  discount_amount: integer("discount_amount").default(0),
  total: integer("total").default(0),
  payment_method: text("payment_method"),
  payment_status: text("payment_status").default("pending"),
  payment_id: text("payment_id"),
  shipping_address_line1: text("shipping_address_line1"),
  shipping_address_line2: text("shipping_address_line2"),
  shipping_city: text("shipping_city"),
  shipping_state: text("shipping_state"),
  shipping_postal_code: text("shipping_postal_code"),
  shipping_country: text("shipping_country").default("BR"),
  shipping_neighborhood: text("shipping_neighborhood"),
  tracking_number: text("tracking_number"),
  tracking_url: text("tracking_url"),
  coupon_code: text("coupon_code"),
  metadata: jsonb("metadata"),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
})
