import { pgTable, text, timestamp, integer, jsonb } from "drizzle-orm/pg-core"

export const astroOrder = pgTable("astro_order", {
  id: text("id").primaryKey(),
  display_id: text("display_id").notNull(),
  status: text("status").default("pending"),
  customer_id: text("customer_id"),
  customer_name: text("customer_name"),
  customer_email: text("customer_email"),
  customer_phone: text("customer_phone"),
  customer_cpf: text("customer_cpf"),
  items: jsonb("items").notNull().default([]),
  subtotal: integer("subtotal").notNull().default(0),
  shipping_cost: integer("shipping_cost").default(0),
  discount_amount: integer("discount_amount").default(0),
  total: integer("total").notNull().default(0),
  payment_method: text("payment_method"),
  payment_status: text("payment_status").default("pending"),
  payment_reference: text("payment_reference"),
  shipping_cep: text("shipping_cep"),
  shipping_street: text("shipping_street"),
  shipping_number: text("shipping_number"),
  shipping_complement: text("shipping_complement"),
  shipping_neighborhood: text("shipping_neighborhood"),
  shipping_city: text("shipping_city"),
  shipping_state: text("shipping_state"),
  tracking_code: text("tracking_code"),
  shipped_at: timestamp("shipped_at"),
  delivered_at: timestamp("delivered_at"),
  cancelled_at: timestamp("cancelled_at"),
  notes: text("notes"),
  coupon_code: text("coupon_code"),
  metadata: jsonb("metadata"),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
})
